Signup
wolox-training/jl-express-js pull request #4
Opened 2018-09-28 15:58 UTC by jersonlopez

## Summary

[Change!] Describe your feature, problems you had, notes, improvements and others.

## Known Issues

[Change!] List any known issue of the feature you are implementing.

## Trello Card

[Change!] Link to the associated Trello card.

2018-09-28 18:41 UTC, picollomartin requested changes
- Missing some validations and catch errors

2018-09-28 18:41 UTC, mpicollo-wolox commented on app/controllers/user.js
> +    res.status(302).send('Error');
Use middleware of errors for validations and add more specific messages

2018-09-28 18:41 UTC, mpicollo-wolox commented on app/controllers/user.js
> +  singUp
Use `exports.signUp` directly

2018-09-28 18:41 UTC, mpicollo-wolox commented on app/controllers/user.js
> +    res.status(200).send('User created correctly.');
Status code is 201 created

2018-09-28 18:41 UTC, mpicollo-wolox commented on app/controllers/user.js
> +  User.createModel(user).then(u => {
Return promise here

2018-09-28 18:41 UTC, mpicollo-wolox commented on app/controllers/user.js
> +  User.createModel(user).then(u => {
Add more descriptive name of variables (`user` instead of `u` for example)

2018-09-28 18:41 UTC, mpicollo-wolox commented on app/controllers/user.js
> +const validateEmail = valor => {
Add a validations file in controller module for all validations

2018-09-28 18:41 UTC, mpicollo-wolox commented on app/controllers/user.js
> +  if (/^\w+([\.-]?\w+)@wolox+(\.\w{2,3})+$/.test(valor)) {
Return condition instead of bool, `return /^\w+([\.-]?\w+)@wolox+(\.\w{2,3})+$/.test(valor)`

2018-09-28 18:41 UTC, mpicollo-wolox commented on app/controllers/user.js
> +const User = require('../models').users;
Group all requires and constants

2018-09-28 18:41 UTC, mpicollo-wolox commented on app/controllers/user.js
> +  if (/^(?=\w*\d)(?=\w*[A-Z])(?=\w*[a-z])\S{8,}$/.test(valor)) {
Same here

2018-09-28 18:41 UTC, mpicollo-wolox commented on app/controllers/user.js
> +  user.firstName = req.body.firstName ? req.body.firstName : '';
This assignations are unnecessary, replace with something like this `const user = req.body ? { firstName: req.body.firstName .... } : {}` if any are undefined nothing is set to `firstName`

2018-09-28 18:41 UTC, mpicollo-wolox commented on app/models/user.js
> +        logger.error(err);
Throw error if something fail in database

2018-09-28 18:41 UTC, mpicollo-wolox commented on app/routes.js
> +  app.post('/users/', [], singUp);
Remove empty middlewares array, is optional

2018-09-28 18:41 UTC, mpicollo-wolox commented on app/models/user.js
> +      .then((success, err) => {
You can pass `()` if parameters are unused

2018-09-28 18:41 UTC, mpicollo-wolox commented on app/models/user.js
> +    return User.create(user)
Remove brackets and return

2018-09-28 18:41 UTC, mpicollo-wolox commented on app/controllers/user.js
> +    res.status(302).send('Error');
400 for bad request, 3xx codes are for redirection and is not the case

2018-09-28 18:41 UTC, mpicollo-wolox commented on app/controllers/user.js
> +const singUp = (req, res) => {
Missing next (you need for errors and call other middlewares)

2018-09-28 18:41 UTC, mpicollo-wolox commented on app/controllers/user.js
> +  if (!validateEmail(user.email) || !validatePassword(user.password)) {
Check mandatory properties and uniqueness of mail

2018-09-28 21:09 UTC, picollomartin requested changes
Missing uniqueness validation of email yet

2018-09-28 21:09 UTC, mpicollo-wolox commented on app/controllers/user.js
> +    return next(errors.emailError('Invalid email'));
Send all errors together

2018-09-28 21:09 UTC, mpicollo-wolox commented on app/controllers/user.js
> +    .catch(err => {
Same as `catch(next)`

2018-09-28 21:09 UTC, mpicollo-wolox commented on app/controllers/validations.js
> +exports.validateEmail = valor => {
Remove brackets and return

2018-09-28 21:09 UTC, mpicollo-wolox commented on app/controllers/validations.js
> +exports.validateEmail = valor => {
change `valor` spanish variable with something more descriptive like `email`

2018-09-28 21:09 UTC, mpicollo-wolox commented on app/models/user.js
> +    return User.create(user)
This is not fixed yet

2018-09-28 21:09 UTC, mpicollo-wolox commented on app/routes.js
> +  app.post('/users/', [], singUp);
This is not fixed yet

2018-09-28 21:12 UTC, jersonlopez commented on app/controllers/user.js
> +    return next(errors.emailError('Invalid email'));
i don't understand you

2018-10-01 12:36 UTC, picollomartin requested changes

2018-10-01 12:36 UTC, mpicollo-wolox commented on app/controllers/user.js
> +  if (!validateEmail(user.email)) signErrors.push(errors.emailError());
Put all logic of errors and validations in `validations` file, for avoid duplicate logic (i see multiple times `if(validation) errrors.push(error)` )

2018-10-01 12:36 UTC, mpicollo-wolox commented on app/controllers/user.js
> +  if (!validateEmail(user.email)) signErrors.push(errors.emailError());
Check for existence of mandatory fields too

2018-10-01 12:36 UTC, mpicollo-wolox commented on app/controllers/user.js
> +  if (signErrors.length) throw errors.signupError(signErrors);
Use a `try/catch` and send by `next`, for more clarity (you can use `await` for existing promises)

2018-10-01 12:36 UTC, mpicollo-wolox commented on app/errors.js
> +exports.EMAIL_ERROR = 'email_is_invalid';
Check all file, i see validations messages and errors messages (only errors messages should be here)

2018-10-01 12:36 UTC, mpicollo-wolox commented on app/errors.js
> +exports.EMAIL_ERROR = 'email_is_invalid';
Validations messages could be in `validations` file

2018-10-01 12:36 UTC, mpicollo-wolox commented on app/middlewares/errors.js
> +  [errors.EMAIL_DUPLICATE_ERROR]: 400,
Not needed of this

2018-10-01 15:38 UTC, picollomartin requested changes
Little changes :muscle:

2018-10-01 15:38 UTC, mpicollo-wolox commented on app/controllers/user.js
> +  const signErrors = await validations(user);
Why `await` if `validations` is not a promise ?

2018-10-01 15:38 UTC, mpicollo-wolox commented on app/models/user.js
> +          const signErrors = [];
This constant is unneeded, you can declare an array like `['User already exist']`

2018-10-01 15:38 UTC, mpicollo-wolox commented on app/controllers/validations.js
> +exports.validations = user => {
Name this like `validateUser` or something similar

2018-10-01 15:38 UTC, mpicollo-wolox commented on app/controllers/validations.js
> +    if (user[member] === undefined) signErrors.push('missing value');
I still see duplication of logic, maybe you can add a function or object for build `signErrors` `const validate = (validations, object) => ....`

2018-10-01 18:30 UTC, picollomartin requested changes
Check validation function again as we talk by slack

2018-10-02 20:53 UTC, picollomartin approved these changes
Check little comment before merge

2018-10-02 20:53 UTC, mpicollo-wolox commented on app/controllers/validations.js
> +const arrayValidations = [validateEmail, validatePassword, validateMissingValues];
Think a better name for this

2018-10-02 21:11 UTC, merged