Album list
wolox-training/jl-express-js pull request #9
Opened 2018-10-10 00:06 UTC by jersonlopez

## Summary

listing albums and their corresponding tests

## Trello Card

[https://trello.com/c/un1CiAo0/31-listado-de-albumes](https://trello.com/c/un1CiAo0/31-listado-de-albumes)

2018-10-10 12:41 UTC, picollomartin requested changes

2018-10-10 12:41 UTC, mpicollo-wolox commented on app/controllers/album.js
> +    const albums = await getAll();
Await seems not necessary here, one simple promise with `.then` and `.catch` should be fine

2018-10-10 12:41 UTC, mpicollo-wolox commented on app/controllers/album.js
> +    res.status(200).send(albums.data);
`albums.data` should be done by service, because is a limitation of dependency used for build that service

2018-10-10 12:41 UTC, mpicollo-wolox commented on config/index.js
> +      url: 'https://jsonplaceholder.typicode.com/albums'
Add a environment variable here ,maybe with a dafault value like  ` process.env.API_URL || 'url'`

2018-10-10 12:41 UTC, mpicollo-wolox commented on config/index.js
> +      url: 'https://jsonplaceholder.typicode.com/albums'
And `/albums` should be added by services, think if you want use `/photos` later :eyes:

2018-10-10 12:41 UTC, mpicollo-wolox commented on test/album.js
> +  describe('/albums/ GET', () => {
Add a failure test for check behavior when service fail

2018-10-10 12:41 UTC, mpicollo-wolox commented on app/services/album.js
> +    throw errors.albumsApiError(err);
Always a 503 http code ? What happen if is a 400 code ?

2018-10-11 19:35 UTC, picollomartin approved these changes

2018-10-11 19:35 UTC, mpicollo-wolox commented on app/controllers/album.js
> +  getAll('/albums')
Return promise here

2018-10-11 21:59 UTC, jersonlopez commented on app/controllers/album.js
> +  getAll('/albums')
is just put ```return getAll('/albums)```?

2018-10-18 21:32 UTC, merged